JOSS submission changes
scikit-learn-contrib/forest-confidence-interval pull request #63
Opened 2017-11-08 11:47 UTC by kpolimis

- added Quinlan 1993 citation
- discussed plotting with standard deviation instead of variance
- syntax changes

2017-11-08 16:00 UTC, arokem requested changes
Looks good. There's a bit of cruft in here pointing to local paths on your machine. Please remove that, and I will merge.

2017-11-08 16:00 UTC, arokem commented on paper/paper.bib
> +	file = {Wageretal2014.pdf:C\:\\Users\\Kivan\\Zotero\\storage\\7ZBXYKH2\\Wageretal2014.pdf:application/pdf}
Please remove the line pointing to the file on your hard-drive

2017-11-08 16:00 UTC, arokem commented on paper/paper.bib
> +	file = {Quinlan1993.pdf:C\:\\Users\\Kivan\\Zotero\\storage\\XNZAZBY7\\Quinlan1993.pdf:application/pdf}
Here as well

2017-11-09 09:27 UTC, kpolimis commented
removed info related to my local machine and updated the paper text and README

2017-11-09 10:33 UTC, merged